DROP TABLE IF EXISTS VAT_COUNTRY;
CREATE TABLE VAT_COUNTRY (ID INT AUTO_INCREMENT  PRIMARY KEY, NAME VARCHAR(50) NOT NULL, CODE VARCHAR(6) NOT NULL, VAT_FORMAT VARCHAR(25));
INSERT INTO VAT_COUNTRY (ID, NAME, CODE, VAT_FORMAT) VALUES (1, 'USA', 'US', '');
INSERT INTO VAT_COUNTRY (id, name, code, VAT_FORMAT) VALUES (2, 'Germany', 'DE', 'DE\d{9}$');
INSERT INTO VAT_COUNTRY (id, name, code, VAT_FORMAT) VALUES (3, 'Austria', 'AT', 'ATU\d{8}$');
INSERT INTO VAT_COUNTRY (id, name, code, VAT_FORMAT) VALUES (4, 'Brazil', 'BR', '');
INSERT INTO VAT_COUNTRY (id, name, code, VAT_FORMAT) VALUES (5, 'Italy', 'IT', '');
INSERT INTO VAT_COUNTRY (id, name, code, VAT_FORMAT) VALUES (6, 'Canada', 'CA', '');