DROP TABLE IF EXISTS VAT_COUNTRY;
CREATE TABLE VAT_COUNTRY (
    ID INT AUTO_INCREMENT  PRIMARY KEY,
    NAME VARCHAR(50) NOT NULL,
    CODE VARCHAR(6) NOT NULL,
    VAT_FORMAT VARCHAR(25),
    UNIQUE (CODE, NAME)
    );

INSERT INTO VAT_COUNTRY (NAME, code, VAT_FORMAT) VALUES ('Germany', 'DE', 'DE\d{9}$');
INSERT INTO VAT_COUNTRY (NAME, code, VAT_FORMAT) VALUES ('Austria', 'AT', 'ATU\d{8}$');